name: Deploy
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm install
 
      - name: Build
        run: npm run docs:build
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          EXTERNAL_REPOSITORY: Wukongyang.github.io
          PUBLISH_DIR: docs-dist
          PUBLISH_BRANCH: master
          commit_message: ${{ github.event.head_commit.message }}
